### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pwntus** [Pwntus/visualbox-frontend#1]
## Project Editor
* [x] Reactive dirty tabs on save
* [x] Folder open state w/ renaming
* [x] File type map -> function so that unknown file types can be resolved
* [x] CTRL + S keybindings
* [ ] Helpers (Integration / Widget)
* [ ] Templates
* [x] ~~Bundle on editor leave (cache might be old in Dashboard)~~ Delete bundle on leave
* [ ] Sourcemaps w/ better error messages?
* [ ] Catch Worker runtime errors in helper console

## Dashboard
* [x] Cleanup everything
* [x] Don't use diff method
* [ ] Save button
* [x] isEditing reset on dashboard leave

## Misc.
* [x] API payload property not nullable
* [x] Fix TSLint errors
* [ ] Color Picker bug with invalid props (live config edit with helper)
* [x] Add integration not cleared on submit/close
* [x] Icons in lists (delete) are not hoverable/clickable
* [x] Search for integrations / widgets (exclude own)
* [x] ~~Clear bundle cache on logout~~ No need to
* [x] Make sure offline driver still complies w/ updated API
* [ ] Bundler queue aborted

**Comment by Pwntus** [comment]
Closed - move from in-browser computing to containers.
